### PR TITLE
Add proxied pages through Web UI

### PR DESCRIPTION
**Pull request by jcrist**
*I'm not 100% settled on this being a good idea/worth it, but it was relatively quick to write up and try out.*

This adds the ability for applications to register additional web pages to proxy through our webui. This allows additional user-provided pages to be accessible through the webui (and thus outside the YARN cluster firewall). Proxied pages can be added and removed dynamically at runtime, and optionally presented as part of the WebUI

Note that our WebUI already passes through the YARN proxy - this adds an additional proxy in our UI that will forward requests to additional pages.

**Existing**
`YARN Proxy -> WebUI`

**With this PR**
`YARN Proxy -> WebUI -> User pages`

### Caveats:
- Due to limitations in the YARN proxy, only `GET` methods are supported in the commonly deployed hadoop versions. In Hadoop 3, support for `PUT` was added, but CDH still deploys 2.6. The Spark web-ui is full of hacks abusing `GET` to get around this.

- Modern web components like web sockets are *not* supported. In particular this means that the dask web ui (https://distributed.readthedocs.io/en/latest/web.html) won't work through the proxy.

- YARN provides a security filter to secure the connection between their proxy and the webui, based on the ip of the requester (https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/WebApplicationProxy.html). This won't work for the proxy from our UI to user pages. This means that a malicious actor *already inside the YARN cluster firewall* (meaning e.g. a coworker) can access the user provided pages provided they can find the addresses. For now I'm punting on this security issue, but it does mean that user provided pages are less secure.

### CODE REVIEW

**Comment by jcrist** [comment]
## Screenshots

Service pages that are presented as part of the web-ui are shown in a dropdown menu. Here we have a single proxied page called `bokeh`.

screen shot 2018-09-14 at 1 17 40 pm

Clicking on this link forwards the request through to the proxied page.

screen shot 2018-09-14 at 1 18 05 pm

**Comment by jcrist** [comment]
cc @superbobry for any potential feedback on this feature they might have.

**Comment by jcrist** [comment]
Also cc @mrocklin for thoughts on providing a simpler, `GET` only dask UI (which could be proxied out of the cluster using this PR).

**Comment by mrocklin** [comment]
The /info pages of the current dask scheduler UI might be informative

**Comment by superbobry** [comment]
This is something I have been thinking about as well in the context of TensorBoard, but I am not sure if it will work with the limitations impose by YARN (GET, no WS). In any case, I'd be happy to give this a try next week!

**Comment by jcrist** [comment]
I've decided to push this through. Punting on the security issue for now (again, it's only insecure if you don't trust your coworkers).

This also adds a `.ui` accessor to the `ApplicationClient`, which includes the address of the web ui, and the methods to add, remove, and query pages.

The test failure is a known periodic issue (on travis only). Merging.

**Pull request merged**
